name: "Build and deploy container images"
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      context: node-ruby/
      dockerfile: node-ruby/Dockerfile
      image-authors: "Patrick Stoeckle"
      image-description: "Node+Ruby"
      image-registry: ghcr.io
      image-name: pstoeckle/docker-images/node-ruby
      image-tag: "24.13.0--4.0.1"
      image-title: "Node+Ruby"
    permissions:
      contents: read
      packages: write
