name: "Check the consistency"

on: {push: {branches: [main]}}

jobs:
  docker-and-github-action-in-sync:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          token: ${{ secrets.PAT }}
      - name: Check consistency/update ci.yml
        id: check
        run: |
          bash utils/check_if_versions_are_aligned.sh
      - name: Update ci.yml if needed
        uses: mikefarah/yq@7ccaf8e700ce99eb3f0f6cef7f5930a0b3c827cd # v4.49.2
        with:
          cmd: yq eval -i '.jobs.docker.with."image-tag"="${{ steps.check.outputs.TAG_VERSION }}"' .github/workflows/ci.yml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: ":arrow_up: chore(deps): align versions"
          branch: main
          file_pattern: .github/workflows/ci.yml
          tagging_message: v${{ steps.check.outputs.TAG_VERSION }}
