name: "Check the consistency"

on: {push: {branches: [main]}}

jobs:
  docker-and-github-action-in-sync:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.PAT }}
      - name: Check consistency/update ci.yml
        id: check
        run: |
          bash utils/check_if_versions_are_aligned.sh
      - name: Update ci.yml if needed
        uses: mikefarah/yq@065b200af9851db0d5132f50bc10b1406ea5c0a8 # v4.50.1
        with:
          cmd: yq eval -i '.jobs.docker.with."image-tag"="${{ steps.check.outputs.TAG_VERSION }}"' .github/workflows/ci.yml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: ":arrow_up: chore(deps): align versions"
          branch: main
          file_pattern: .github/workflows/ci.yml
          tagging_message: v${{ steps.check.outputs.TAG_VERSION }}
